apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${common_name}
spec:
  secretName: ${secret_name}
  commonName: ${common_name}
  dnsNames:
    - ${common_name}
  duration: ${duration_hrs}h
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ven-issuer
    kind: VenafiClusterIssuer
    group: jetstack.io
